### ISSUE TITLE
Environment is Broken on Ubuntu 20.04

### ISSUE THREAD

**Issue by sebbyjp** [charlesjsun/ReLMM#2]
Hello!

I would like to run one of the examples but `conda env create -f environment.yml` gives the following error:

```
Pip subprocess error:
ERROR: Could not find a version that satisfies the requirement mkl-fft==1.1.0 (from versions: 1.2.0, 1.3.0, 1.3.1)
ERROR: No matching distribution found for mkl-fft==1.1.0

failed

CondaEnvException: Pip failed
```

Ubuntu version: 20.04.4 LTS 
conda version: 4.12.0
pip version: 22.1.2
python: 3.7.13

**Comment by jborbik** [comment]
I have fixed that in https://github.com/charlesjsun/ReLMM/commit/c10a3081f912c50004df4b4b64efbd2835180edd
Thanks for letting us know!
